2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Configure stats pid to 51193
2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Loading settings from /Users/aida/.config/wandb/settings
2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Loading settings from /Users/aida/PycharmProjects/ec523-project/ec523-project/code/wandb/settings
2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-03 18:15:10,255 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'code/cleanDQN.py', 'program_abspath': '/Users/aida/PycharmProjects/ec523-project/ec523-project/code/cleanDQN.py', 'program': '/Users/aida/PycharmProjects/ec523-project/ec523-project/code/cleanDQN.py'}
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_init.py:_log_setup():521] Logging user logs to /Users/aida/PycharmProjects/ec523-project/ec523-project/code/wandb/run-20240403_181510-d3zm3j5e/logs/debug.log
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/aida/PycharmProjects/ec523-project/ec523-project/code/wandb/run-20240403_181510-d3zm3j5e/logs/debug-internal.log
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_init.py:init():561] calling init triggers
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'exp_name': 'cleanDQN', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'cleanRL', 'wandb_entity': None, 'capture_video': False, 'save_model': False, 'upload_model': False, 'hf_entity': '', 'env_id': 'CartPole-v1', 'total_timesteps': 500000, 'learning_rate': 0.00025, 'num_envs': 1, 'buffer_size': 10000, 'gamma': 0.99, 'tau': 1.0, 'target_network_frequency': 500, 'batch_size': 128, 'start_e': 1, 'end_e': 0.05, 'exploration_fraction': 0.5, 'learning_starts': 10000, 'train_frequency': 10}
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_init.py:init():611] starting backend
2024-04-03 18:15:10,256 INFO    MainThread:51193 [wandb_init.py:init():615] setting up manager
2024-04-03 18:15:10,257 INFO    MainThread:51193 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-03 18:15:10,259 INFO    MainThread:51193 [wandb_init.py:init():623] backend started and connected
2024-04-03 18:15:10,264 INFO    MainThread:51193 [wandb_init.py:init():715] updated telemetry
2024-04-03 18:15:10,285 INFO    MainThread:51193 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-03 18:16:40,623 ERROR   MainThread:51193 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-04-03 18:16:42,645 ERROR   MainThread:51193 [wandb_init.py:init():1199] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/aida/PycharmProjects/ec523-project/ec523-project/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
  File "/Users/aida/PycharmProjects/ec523-project/ec523-project/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
